### ISSUE TITLE
1.16.5版本mod登录修复进度

### ISSUE THREAD

**Issue by Doctor-Yin** [Forsaken-Land/doctor#1]
目前已知进度:
- [x]  Ex Nihilo : Sequentia
- [x]  ExtendedCrafting
- [x]  SilentGear
- [x]  AstralSorcery
- [x]  Environmental 
- [x]   Obfuscate

未知:
- [x] #2

**Comment by yunling520** [comment]
未找到协议包 ChannelAndId(channel=obfuscate:handshake,id=1) 对应的解码实现.
连接断开 {"translate":"multiplayer.disconnect.slow_login"}

obfuscate :[mcmod](https://www.mcmod.cn/class/1217.html) [github](https://github.com/MrCrayfish/Obfuscate)

**Comment by Doctor-Yin** [comment]
重写fml2登录功能,完全修复
